name: 'AI Code Review Action'
description: 'Perform code reviews and comment on diffs using OpenAI API.'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token to interact with the repository.'
    required: true
  OPENAI_API_KEY:
    description: 'OpenAI API key for GPT.'
    required: true
  OPENAI_API_MODEL:
    description: 'OpenAI API model.'
    required: false
    default: 'gpt-4o'
  role_description:
    description: 'Role description for the AI.'
    required: false
    default: 'You are an expert developer.'
  max_tokens:
    description: 'Maximum number of tokens that can be generated per analysis.'
    required: false
    default: '700'
  exclude:
    description: 'Glob patterns to exclude files from the diff analysis'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'aperture'
  color: 'green'
